name: pysnowpark_de
channels:
  - https://repo.anaconda.com/pkgs/snowflake
  - nodefaults
dependencies:
  - python=3.8
  - pip
  - pip:
    # Snowpark
    - snowflake-snowpark-python[pandas]
    - snowflake-cli-labs
