snowsql_config_path = "/Users/druthven/.snowsql/config"
snowsql_connection_name = "dev"

[default]
input_parameters = "(temp_f float)"
return_type = "float"
file = "app.zip"
name = "fahrenheit_to_celsius_udf"
handler = "app.main"
execute_as_caller = true

[dev]
database = "HOL_DE_DB"
schema = "ANALYTICS"
warehouse = "HOL_DE_WH"
role = "HOL_DE_ROLE"
overwrite = true